### ISSUE TITLE
Question about handling publications

### ISSUE THREAD

**Issue by erinmr** [DarwinCV/automated-CV#1]
Hi - Thanks so much for doing all of this work! I cloned the repo and was able to update my CV through the spreadsheet. I'd like to add publications and wondered if you have thoughts on how to handle those. Thanks again - this makes life so much simpler!

**Comment by DarwinCV** [comment]
You could add inside the 'entries' tab the information of your publications like this 
![Captura de Pantalla 2022-03-07 a la(s) 20 20 19](https://user-images.githubusercontent.com/40300400/157146992-1b5807b8-1f68-4904-bc43-5da43238d488.png)

CV$entries_data %>% 
  filter(section == 'academic_articles') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`}"),
    with = title,
    where = loc,
    why = description_bullets
  )

Or if you have some design of how you expect the information to be displayed I could think of some function.

I'm glad you found this useful.

**Comment by erinmr** [comment]
Thanks so much! I will give this a go in the next few days and report back.

**Comment by erinmr** [comment]
Hi @DarwinCV - This worked really well and is what I need for now. Ideally, I'd be able to keep the formatting of the citation but something happening and italics/bold get stripped out even when I do asis. For now though - here's my CV!   
[CV.pdf](https://github.com/DarwinCV/automated-CV/files/8216669/CV.pdf) Thank you so so much! I love this approach and am excited to continue to use it and easily update.

**Comment by DarwinCV** [comment]
@erinmr Thank you very much, any suggestion for improvement will be welcome.
